version: '3.1'

services:
  backend:
    restart: always
    build: ./backend
    volumes:
      - ./backend:${PROJECT_ROOT}
      - ./.env:${PROJECT_ROOT}/.env
    expose:
      - ${UWSGI_PORT}
    ports:
      - ${UWSGI_PORT_RANGE}:${UWSGI_PORT_RANGE}
#    command: daphne project.asgi:application -b 0.0.0.0 -p ${UWSGI_PORT}
    command: python manage.py runserver 0:${UWSGI_PORT}
    depends_on:
      - postgres
      - memcached
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_DB=${DB_NAME}
    volumes:
    - postgres_data:/var/lib/postgresql/data
  memcached:
    image: memcached:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
  frontend:
    build: ./frontend
    command: ["npm", "start"]
    volumes:
      - ./frontend:${PROJECT_ROOT}
      - node-modules:${PROJECT_ROOT}/node_modules
    ports:
      - ${FRONTEND_PORT}:3000
    stdin_open: true
  nginx:
    image: nginx
    restart: always
    ports:
    - ${NGINX_PORT}:80
    volumes:
    - ./nginx/sites-enabled:/etc/nginx/sites-enabled
    - ./nginx/nginx.conf:/etc/nginx/nginx.conf
  elasticsearch:
    image: elasticsearch:7.9.0
    restart: always
    ports:
    - ${ELASTICPORT}:9200
    environment:
    - discovery.type=single-node
volumes:
  postgres_data: {}
  node-modules: {}