version: '3.1'

services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
    - POSTGRES_USER=${DB_USER}
    - POSTGRES_PASSWORD=${DB_PASSWORD}
    - POSTGRES_DB=${DB_NAME}
    volumes:
    - postgres_data:/var/lib/postgresql/data
  memcached:
    image: memcached:latest
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "2"
volumes:
  postgres_data: {}